feat(offer): Change undo lapse action state to sent
artsy/convection pull request #1053
Opened 2021-04-30 10:43 UTC by angelagasparyan

![ksnip_20210430-143620](https://user-images.githubusercontent.com/30925799/116684041-787a5f00-a9c1-11eb-9c58-55c93836a7fd.png)
![ksnip_20210430-143528](https://user-images.githubusercontent.com/30925799/116684048-7ca67c80-a9c1-11eb-8552-0393e7a3616e.png)

Refs CX-1383

2021-04-30 18:54 UTC, bhoggard commented
I left a [comment](https://artsyproduct.atlassian.net/browse/CX-1383?focusedCommentId=36873) in the ticket about not sending the email in this case.

2021-04-30 18:54 UTC, bhoggard requested changes
Don't send email in this case.

2021-04-30 20:31 UTC, angelagasparyan commented
![ksnip_20210501-001956](https://user-images.githubusercontent.com/30925799/116751048-81e0e700-aa14-11eb-86ae-88b53a3a5ae8.png)

2021-05-01 00:54 UTC, bhoggard approved these changes

2021-05-01 00:54 UTC, merged