fix(CX-3004): update email address to sell@
artsy/convection pull request #1362
Opened 2022-11-24 17:54 UTC by MrSltun

This PR updates the sending email address from consign@ to sell@

2022-11-25 09:32 UTC, MounirDhahri requested changes
This looks good to me. There is only one final thing required I believe before merging this.
I see that the email is still consign@artsy in hokusai
<img width="623" alt="Screenshot 2022-11-25 at 10 29 32" src="https://user-images.githubusercontent.com/11945712/203947426-b13cd351-d9a0-44cc-9973-84dbc9df39c6.png">


It's also still missing within the S3 artsy citadel bucket. Would you mind adding it there

For both instruction, you can follow the steps here  https://artsy.slack.com/archives/CP9P4KR35/p1668617664353739

2022-11-25 10:10 UTC, lordkiz commented on config/initializers/_config.rb
> +    admin_email_address: ENV['ADMIN_EMAIL_ADDRESS'] || 'sell@artsy.net',
Is the env var also updated?
And if so, we also need to confirm it doesn't break stuffs elsewhere.

2022-11-25 13:01 UTC, dariakoko reviewed
LGTM!
Is it all required changes? I suppose we should touch some other repos too, no? 🤔

2022-11-28 13:34 UTC, MrSltun commented
@MounirDhahri I just updated the env on both the S3 and on hokusai, please check and let me know :)

2022-11-28 13:53 UTC, MounirDhahri approved these changes
Niiice Thanks @MrSltun

2022-11-28 13:53 UTC, merged